# -*- coding: utf-8 -*-
"""fg3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PItJdnCiSIprxo3YcZcsBlSbVg9YQDYW
"""

import math
import datetime
from abc import ABC, abstractmethod


class Color:
    def __init__(self, color):
        self._color = None
        self.color = color

    @property
    def color(self):
        return self._color

    @color.setter
    def color(self, value):
        if isinstance(value, str) and value.strip():
            self._color = value
        else:
            raise ValueError("El color debe ser una cadena de texto no vacía.")

    def __str__(self):
        return f"Color: {self.color}"


class FiguraGeometrica(ABC):
    def __init__(self, alto, ancho):
        self._alto = None
        self._ancho = None
        self.alto = alto
        self.ancho = ancho

    @property
    def alto(self):
        return self.__alto

    @alto.setter
    def alto(self, value):
        if isinstance(value, (int, float)) and value > 0:
            self.__alto = float(value)
        else:
            raise ValueError("El alto debe ser un número positivo.")

    @property
    def ancho(self):
        return self._ancho

    @ancho.setter
    def ancho(self, value):
        if isinstance(value, (int, float)) and value > 0:
            self._ancho = float(value)
        else:
            raise ValueError("El ancho debe ser un número positivo.")

    @abstractmethod
    def area(self):
        pass

    @abstractmethod
    def perimetro(self):
        pass

    def __str__(self):
        return f"figurasgemetricas = Alto : {self.alto}, Ancho: {self.ancho}"


class Rectangulo(FiguraGeometrica, Color):
    def __init__(self, alto, ancho, color):
        FiguraGeometrica.__init__(self, alto, ancho)
        Color.__init__(self, color)

    def area(self):
        return self.alto * self.ancho

    def perimetro(self):
        return 2 * (self.alto + self.ancho)

    def __str__(self):
        return f"Rectángulo -> {FiguraGeometrica.__str__(self)}, " \
               f"{Color.__str__(self)}"


class Cuadrado(FiguraGeometrica, Color):
    def __init__(self, lado, color):
        FiguraGeometrica.__init__(self, lado, lado)
        Color.__init__(self, color)

    @property
    def alto(self):
        return self.__alto

    @alto.setter
    def alto(self, value):
        if isinstance(value, (int, float)) and value > 0:
            v = float(value)
            self.__alto = v
            self.__ancho = v
        else:
            raise ValueError("El lado del cuadrado debe ser un número "
                             "positivo.")

    @property
    def ancho(self):
        return self.__ancho

    @ancho.setter
    def ancho(self, value):
        self.alto = value

    def area(self):
        return self.alto * self.alto

    def perimetro(self):
        return 4 * self.alto

    def __str__(self):
        return f"Cuadrado -> Lado: {self.alto}, {Color.__str__(self)}"


class Circunferencia(FiguraGeometrica, Color):
    def __init__(self, diametro, color):
        FiguraGeometrica.__init__(self, diametro, diametro)
        Color.__init__(self, color)

    @property
    def alto(self):
        return self._alto

    @alto.setter
    def alto(self, value):
        if isinstance(value, (int, float)) and value > 0:
            v = float(value)
            self._alto = v
            self._ancho = v
        else:
            raise ValueError("El diámetro de la circunferencia debe ser un "
                             "número positivo.")

    @property
    def ancho(self):
        return self._ancho

    @ancho.setter
    def ancho(self, value):
        self.alto = value

    def area(self):
        radio = self.alto / 2.0
        return math.pi * (radio ** 2)

    def perimetro(self):
        return math.pi * self.alto

    def __str__(self):
        return f"Circunferencia -> Diámetro: {self.alto}, " \
               f"{Color.__str__(self)}"


def sumar_areas(figuras_geometricas):
    suma_areas = 0
    for figura in figuras_geometricas:
        suma_areas += figura.area()
    return suma_areas


def sumar_perimetros(figuras_geometricas):
    suma_perimetros = 0
    for figura in figuras_geometricas:
        suma_perimetros += figura.perimetro()
    return suma_perimetros


if __name__ == "__main__":
    now = datetime.datetime.now()
    fecha_hora_str = now.strftime('%Y-%m-%d %H:%M:%S')
    print(f"--- Ejecución del Código - {fecha_hora_str} ---\n")

    lista_figuras = []

    cuadrado = Cuadrado(5, 'Rojo')
    rectangulo = Rectangulo(alto=10, ancho=15, color='Rojo')
    circulo = Circunferencia(diametro=8, color='Azul')

    lista_figuras.append(cuadrado)
    lista_figuras.append(rectangulo)
    lista_figuras.append(circulo)

    print("--- Demostración Individual de Figuras ---")
    for fig in lista_figuras:
        print(fig)
        print(f"  Área: {fig.area():.2f} | Perímetro: {fig.perimetro():.2f}\n")

    print("--- Demostración de Funciones Polimórficas ---")
    total_areas = sumar_areas(lista_figuras)
    total_perimetros = sumar_perimetros(lista_figuras)

    print(f"Suma Total de Áreas: {total_areas:.2f}")
    print(f"Suma Total de Perímetros: {total_perimetros:.2f}\n")

    print("--- Demostración de Validaciones ---")
    try:
        print("Intentando crear rectángulo con medidas negativas...")
        Rectangulo(-10, 15, 'Verde')
    except ValueError as e:
        print(f"ERROR ATRAPADO: {e}")

    try:
        print("\nIntentando cambiar el lado del cuadrado a negativo...")
        cuadrado.alto = -5
    except ValueError as e:
        print(f"ERROR ATRAPADO: {e}")

    print(f"\n--- Fin de la Demostración - {fecha_hora_str} ---")